# ============================================================
# CIVICMIND AI — RECEIPT SERVICE
# ============================================================
#
# Purpose:
#   Create a structured complaint receipt after CivicMind AI
#   processes a citizen complaint.
#
# The receipt acts as:
#   - Confirmation of complaint submission
#   - Citizen reference record
#   - Tracking reference
#   - Summary of AI processing
#
# This service does NOT:
#   - Save directly to the database
#   - Handle authentication
#   - Generate PDF files
#   - Handle HTTP requests
#
# Those responsibilities belong to other layers.
#
# ============================================================

from datetime import datetime, timezone
from typing import Optional
import uuid


# ============================================================
# RECEIPT STATUS
# ============================================================

DEFAULT_STATUS = "SUBMITTED"


# ============================================================
# RECEIPT PREFIX
# ============================================================

RECEIPT_PREFIX = "CMA"


# ============================================================
# TRACKING NUMBER GENERATOR
# ============================================================

def generate_tracking_number() -> str:
    """
    Generate a human-friendly complaint tracking number.

    Example:
        CMA-20260823-A7F3D9

    Format:
        CMA-YYYYMMDD-XXXXXX
    """

    now = datetime.now(
        timezone.utc
    )

    unique_part = uuid.uuid4().hex[:6].upper()

    return (
        f"{RECEIPT_PREFIX}-"
        f"{now.strftime('%Y%m%d')}-"
        f"{unique_part}"
    )


# ============================================================
# RECEIPT ID GENERATOR
# ============================================================

def generate_receipt_id() -> str:
    """
    Generate a unique internal receipt identifier.

    Example:
        RCPT-8A72F91C
    """

    unique_part = uuid.uuid4().hex[:8].upper()

    return f"RCPT-{unique_part}"


# ============================================================
# TIMESTAMP
# ============================================================

def generate_timestamp() -> str:
    """
    Generate a UTC ISO-8601 timestamp.

    Example:
        2026-08-23T18:30:45+00:00
    """

    return datetime.now(
        timezone.utc
    ).isoformat()


# ============================================================
# TEXT NORMALIZATION
# ============================================================

def normalize_text(
    text: Optional[str],
) -> str:
    """
    Clean user-provided text before putting it into the
    receipt.
    """

    if not text:
        return ""

    return " ".join(
        text.strip().split()
    )


# ============================================================
# CONFIDENCE NORMALIZATION
# ============================================================

def normalize_confidence(
    confidence: Optional[float],
) -> float:
    """
    Normalize confidence values to the range 0.0–1.0.
    """

    if confidence is None:
        return 0.0

    try:
        value = float(confidence)
    except (
        TypeError,
        ValueError,
    ):
        return 0.0

    return round(
        max(
            0.0,
            min(
                value,
                1.0,
            ),
        ),
        2,
    )


# ============================================================
# RECEIPT CREATION
# ============================================================

def create_receipt(
    complaint_id: int | str,
    citizen_name: str,
    citizen_email: str,
    complaint_text: str,
    category: str,
    priority: str,
    department: str,
    classification_confidence: Optional[float] = None,
    priority_confidence: Optional[float] = None,
    department_confidence: Optional[float] = None,
    status: str = DEFAULT_STATUS,
) -> dict:
    """
    Create a structured CivicMind AI complaint receipt.

    Parameters:
        complaint_id:
            Database complaint ID or temporary complaint
            identifier.

        citizen_name:
            Citizen's full name.

        citizen_email:
            Citizen's email address.

        complaint_text:
            Original complaint submitted by the citizen.

        category:
            Category generated by ai_classifier.py.

        priority:
            Priority generated by priority_predictor.py.

        department:
            Department generated by department_router.py.

        classification_confidence:
            AI classifier confidence.

        priority_confidence:
            Priority predictor confidence.

        department_confidence:
            Department router confidence.

        status:
            Initial complaint status.

    Returns:
        A structured receipt dictionary.
    """

    # --------------------------------------------------------
    # Normalize input
    # --------------------------------------------------------

    citizen_name = normalize_text(
        citizen_name
    )

    citizen_email = normalize_text(
        citizen_email
    )

    complaint_text = normalize_text(
        complaint_text
    )

    category = normalize_text(
        category
    )

    priority = normalize_text(
        priority
    ).upper()

    department = normalize_text(
        department
    )

    status = normalize_text(
        status
    ).upper()

    # --------------------------------------------------------
    # Generate identifiers
    # --------------------------------------------------------

    receipt_id = generate_receipt_id()

    tracking_number = generate_tracking_number()

    submitted_at = generate_timestamp()

    # --------------------------------------------------------
    # Normalize confidence values
    # --------------------------------------------------------

    classification_confidence = (
        normalize_confidence(
            classification_confidence
        )
    )

    priority_confidence = (
        normalize_confidence(
            priority_confidence
        )
    )

    department_confidence = (
        normalize_confidence(
            department_confidence
        )
    )

    # --------------------------------------------------------
    # Calculate overall AI confidence
    # --------------------------------------------------------

    confidence_values = [
        classification_confidence,
        priority_confidence,
        department_confidence,
    ]

    valid_confidences = [
        value
        for value in confidence_values
        if value > 0
    ]

    if valid_confidences:

        overall_confidence = round(
            sum(valid_confidences)
            / len(valid_confidences),
            2,
        )

    else:

        overall_confidence = 0.0

    # --------------------------------------------------------
    # Build receipt
    # --------------------------------------------------------

    receipt = {

        "receipt_id":
            receipt_id,

        "tracking_number":
            tracking_number,

        "complaint_id":
            complaint_id,

        "status":
            status,

        "submitted_at":
            submitted_at,

        "citizen": {

            "name":
                citizen_name,

            "email":
                citizen_email,
        },

        "complaint": {

            "description":
                complaint_text,

            "category":
                category,

            "priority":
                priority,

            "department":
                department,
        },

        "ai_analysis": {

            "classification_confidence":
                classification_confidence,

            "priority_confidence":
                priority_confidence,

            "department_confidence":
                department_confidence,

            "overall_confidence":
                overall_confidence,
        },
    }

    return receipt


# ============================================================
# RECEIPT SUMMARY
# ============================================================

def get_receipt_summary(
    receipt: dict,
) -> dict:
    """
    Return a lightweight summary suitable for frontend cards,
    dashboards, or tracking pages.
    """

    return {

        "tracking_number":
            receipt.get(
                "tracking_number"
            ),

        "complaint_id":
            receipt.get(
                "complaint_id"
            ),

        "status":
            receipt.get(
                "status"
            ),

        "submitted_at":
            receipt.get(
                "submitted_at"
            ),

        "category":
            receipt.get(
                "complaint",
                {},
            ).get(
                "category"
            ),

        "priority":
            receipt.get(
                "complaint",
                {},
            ).get(
                "priority"
            ),

        "department":
            receipt.get(
                "complaint",
                {},
            ).get(
                "department"
            ),
    }


# ============================================================
# RECEIPT VALIDATION
# ============================================================

def validate_receipt(
    receipt: dict,
) -> bool:
    """
    Validate that the receipt contains the minimum required
    information.

    Returns:
        True  → valid receipt
        False → incomplete receipt
    """

    required_top_level_fields = [
        "receipt_id",
        "tracking_number",
        "complaint_id",
        "status",
        "submitted_at",
        "citizen",
        "complaint",
        "ai_analysis",
    ]

    for field in required_top_level_fields:

        if field not in receipt:

            return False

    citizen = receipt.get(
        "citizen",
        {},
    )

    complaint = receipt.get(
        "complaint",
        {},
    )

    required_citizen_fields = [
        "name",
        "email",
    ]

    required_complaint_fields = [
        "description",
        "category",
        "priority",
        "department",
    ]

    for field in required_citizen_fields:

        if field not in citizen:

            return False

    for field in required_complaint_fields:

        if field not in complaint:

            return False

    return True